# Generated by Django 2.1.2 on 2019-10-10 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Place', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Password', models.CharField(max_length=8)),
                ('Confirmpassword', models.CharField(max_length=8)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Place', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Village', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=8)),
                ('Confirmpassword', models.CharField(max_length=8)),
                ('Status', models.BooleanField(default=False)),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ontology.District')),
            ],
        ),
    ]
