# Generated by Django 2.1.2 on 2019-10-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='District',
            field=models.CharField(choices=[('kasaragod', 'Kasaragod'), ('kannur', 'Kannur'), ('kozhikode', 'Kozhikode'), ('wayanad', 'Wayanad'), ('malappuram', 'Malappuram'), ('palakkad', 'Palakkad'), ('thrissur', 'Thrissur')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
