# Generated by Django 2.1.2 on 2019-10-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0002_auto_20191010_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
