# Generated by Django 2.1.2 on 2019-10-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
