# Generated by Django 2.1.2 on 2019-10-24 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0004_auto_20191023_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnerId', models.PositiveIntegerField()),
                ('OwnerName', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=40)),
                ('Price', models.PositiveIntegerField()),
                ('Rent_Amount', models.PositiveIntegerField()),
                ('Quantity', models.PositiveIntegerField()),
                ('Photo', models.ImageField(upload_to='')),
                ('Use', models.TextField()),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ontology.Category')),
            ],
        ),
    ]
