# Generated by Django 2.1.2 on 2019-10-25 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('Total_Amount', models.PositiveIntegerField()),
                ('Type', models.CharField(max_length=50)),
                ('Status', models.CharField(default='Pending', max_length=50)),
                ('Dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontology.Dealer')),
                ('Farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontology.Farmer')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontology.Product')),
            ],
        ),
    ]
