# Generated by Django 2.1.2 on 2019-10-28 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification', models.TextField()),
                ('DealerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontology.Dealer')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeCenterNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification', models.TextField()),
            ],
        ),
    ]
