# Generated by Django 2.1.2 on 2019-10-30 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0010_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_of_Days', models.PositiveIntegerField()),
                ('Total_Amount', models.PositiveIntegerField()),
                ('Rent_Date', models.DateTimeField(null=True)),
                ('Return_Date', models.DateTimeField(blank=True, null=True)),
                ('Status', models.CharField(default='Pending', max_length=50)),
                ('Farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontology.Farmer')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontology.Product')),
            ],
        ),
    ]
