from django.urls import path
from . import views 

app_name='ontology'

urlpatterns=[
    path('', views.index, name='index'),
    path('farmer_reg/', views.farmer_reg, name='farmer_reg'),
    path('dealer_reg/', views.dealer_reg, name='dealer_reg'),
    path('knowledge_center_home/', views.knowledge_center_home, name='knowledge_center_home'),
    path('manage_farmer/', views.manage_farmer, name='manage_farmer'),
    path('<int:id>/approve_farmer/', views.approve_farmer, name='approve_farmer'),
    path('<int:id>/reject_farmer/', views.reject_farmer, name='reject_farmer'),
    path('view_all_farmers/', views.view_all_farmers, name='view_all_farmers'),
    path('farmer_home/<int:id>/', views.farmer_home, name='farmer_home'),
    path('dealer_home/<int:id>/', views.dealer_home, name='dealer_home'),
    path('view_farmer_profile/<int:id>/', views.view_farmer_profile, name='view_farmer_profile'),
    path('view_dealer_profile/<int:id>/', views.view_dealer_profile, name='view_dealer_profile'),
    path('view_product_cat/', views.view_product_cat, name='view_product_cat'),
    path('show_products/<int:id>/', views.show_products, name='show_products'),
    path('select_category/<int:id>/', views.select_category, name='select_category'),
    path('add_product/<int:id>/', views.add_product, name='add_product'),
    path('show_single_product/<int:id>/', views.show_single_product, name='show_single_product'),
    path('farmer_buy_product/<int:id>/', views.farmer_buy_product, name='farmer_buy_product'),
    path('online_payment/<int:id>/', views.online_payment, name='online_payment'),
    path('view_all_products/', views.view_all_products, name='view_all_products'),
    path('update_product_stock/<int:id>/', views.update_product_stock, name='update_product_stock'),
    path('knowledge_center_view_all_products/', views.knowledge_center_view_all_products, name='knowledge_center_view_all_products'),
    path('add_knowledge_center_notification/', views.add_knowledge_center_notification, name='add_knowledge_center_notification'),
    path('add_dealer_notification/<int:id>/', views.add_dealer_notification, name='add_dealer_notification'),
    path('admin_view_notification/', views.admin_view_notification, name='admin_view_notification'),
    path('dealer_view_notification/', views.dealer_view_notification, name='dealer_view_notification'),
    path('farmer_view_notification/', views.farmer_view_notification, name='farmer_view_notification'),
    path('farmer_view_payment_detail/', views.farmer_view_payment_detail, name='farmer_view_payment_detail'),
    path('add_knowledge_center_service/', views.add_knowledge_center_service, name='add_knowledge_center_service'),
    path('farmer_view_services/', views.farmer_view_services, name='farmer_view_services'),
    path('dealer_view_payment_detail/', views.dealer_view_payment_detail, name='dealer_view_payment_detail'),
    path('send_complaint/<int:id>/', views.send_complaint, name='send_complaint'),
    path('admin_view_complaints/', views.admin_view_complaints, name='admin_view_complaints'),
    path('send_complaint_reply/<int:id>/', views.send_complaint_reply, name='send_complaint_reply'),
    path('add_question/<int:id>/', views.add_question, name='add_question'),
    path('admin_view_questions/', views.admin_view_questions, name='admin_view_questions'),
    path('send_question_reply/<int:id>/', views.send_question_reply, name='send_question_reply'),
    path('logout/', views.logout, name='logout'),
    path('farmer_change_password/<int:id>/', views.farmer_change_password, name='farmer_change_password'),
    path('dealer_change_password/<int:id>/', views.dealer_change_password, name='dealer_change_password'),
    path('farmer_rent_equipment/<int:id>/', views.farmer_rent_equipment, name='farmer_rent_equipment'),
    path('rent_equipment/', views.rent_equipment, name='rent_equipment'),
    path('show_single_equipment/<int:id>/', views.show_single_equipment, name='show_single_equipment'),
    path('farmer_page',views.farmer_page,name='farmer_page'),
    path('dealer_page',views.dealer_page,name='dealer_page'),
    path('admin_page',views.admin_page,name='admin_page'),
    ]
